"""Self-contained interactive browser view for a Graphify C4 projection."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from graphify.paths import write_text_atomic


_TEMPLATE = """<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>C4 Architecture</title>
<style>
:root { color-scheme: light dark; font: 15px system-ui, sans-serif; }
body { margin: 0; background: #f6f8fb; color: #18212f; }
header { padding: 20px 28px; background: #172033; color: #fff; }
header h1 { margin: 0 0 4px; font-size: 22px; } header p { margin: 0; opacity: .8; }
main { padding: 22px 28px; max-width: 1500px; margin: auto; }
.controls { display: flex; flex-wrap: wrap; gap: 12px; align-items: end; margin-bottom: 20px; }
label { display: grid; gap: 5px; font-weight: 600; } select, button { font: inherit; padding: 7px 10px; border-radius: 6px; border: 1px solid #b8c2d3; background: #fff; color: #18212f; }
button { cursor: pointer; } .summary { color: #526174; margin: 0 0 14px; }
.graph-frame { min-height: 430px; border: 1px solid #cbd5e1; border-radius: 10px; overflow: hidden; background: radial-gradient(circle at 50% 10%, #fff, #eef3f9); position: relative; }
.architecture-graph { display: block; width: 100%; height: min(60vw, 660px); min-height: 430px; touch-action: none; cursor: grab; }
.architecture-graph.dragging { cursor: grabbing; } .architecture-graph .edge { stroke-width: 2; fill: none; opacity: .8; } .architecture-graph .edge.observed { stroke: #c15a00; stroke-dasharray: 6 4; } .architecture-graph .edge.declared { stroke: #16803b; }
.architecture-graph .node { cursor: pointer; } .architecture-graph .node rect { fill: #fff; stroke: #3867d6; stroke-width: 2; rx: 9; } .architecture-graph .node:hover rect { stroke-width: 4; filter: drop-shadow(0 2px 5px #17203333); } .architecture-graph .node text { fill: #18212f; pointer-events: none; } .architecture-graph .node .type { fill: #526174; font-size: 11px; font-weight: 700; letter-spacing: .4px; } .architecture-graph .node .name { font-size: 15px; font-weight: 700; }
.legend { position: absolute; top: 10px; right: 12px; display: flex; gap: 10px; flex-wrap: wrap; font-size: 12px; color: #526174; background: #ffffffd9; border-radius: 6px; padding: 5px 8px; } .legend i { display: inline-block; width: 18px; border-top: 3px solid #16803b; vertical-align: middle; margin-right: 4px; } .legend i.observed { border-color: #c15a00; border-top-style: dashed; }
.graph-help { font-size: 13px; color: #526174; margin: 8px 0 0; }
.cards { display: grid; grid-template-columns: repeat(auto-fill, minmax(230px, 1fr)); gap: 12px; }
.card { border: 1px solid #cbd5e1; border-left: 5px solid #3867d6; border-radius: 8px; background: #fff; padding: 12px; cursor: pointer; text-align: left; min-height: 88px; }
.card:hover { box-shadow: 0 2px 10px #17203324; } .type { color: #526174; font-size: 12px; text-transform: uppercase; font-weight: 700; } .name { margin: 6px 0 3px; font-weight: 700; } .id { color: #66758a; font: 12px ui-monospace, SFMono-Regular, monospace; overflow-wrap: anywhere; }
section { margin-top: 30px; } h2 { font-size: 18px; } table { width: 100%; border-collapse: collapse; background: #fff; border: 1px solid #cbd5e1; } th, td { padding: 9px 10px; border-bottom: 1px solid #e2e8f0; text-align: left; vertical-align: top; } th { background: #edf2f7; } .observed { color: #9c3b00; } .declared { color: #166534; } .empty { padding: 18px; background: #fff; border: 1px dashed #94a3b8; border-radius: 8px; }
@media (prefers-color-scheme: dark) { body { background: #0d1524; color: #e5e7eb; } header { background: #111827; } select, button, .card, table, .empty { background: #162033; color: #e5e7eb; border-color: #334155; } th { background: #1d2a40; } th, td { border-color: #334155; } .summary,.type,.id,.graph-help,.legend { color: #a8b6c8; } .graph-frame { border-color: #334155; background: radial-gradient(circle at 50% 10%, #1b2a43, #0d1524); } .legend { background: #162033e8; } .architecture-graph .node rect { fill: #162033; } .architecture-graph .node text { fill: #e5e7eb; } .architecture-graph .node .type { fill: #a8b6c8; } }
</style></head><body>
<header><h1>C4 Architecture</h1><p>Declared contract and observed Graphify code evidence</p></header>
<main><div class="controls"><label>Level <select id="level"><option value="context">Context</option><option value="container" selected>Container</option><option value="component">Component</option><option value="code">Code</option></select></label><label>Focus <select id="focus"></select></label><button id="reset">Reset focus</button></div><p class="summary" id="summary"></p><section><h2>Architecture graph</h2><div class="graph-frame"><div class="legend"><span><i></i>Declared</span><span><i class="observed"></i>Observed code evidence</span></div><svg class="architecture-graph" id="architecture-graph" viewBox="0 0 1200 660" aria-label="Interactive architecture graph"></svg></div><p class="graph-help">Click a node to drill down. Drag to pan; use the mouse wheel to zoom; double-click empty space to reset the view.</p></section><section><h2>Elements</h2><div class="cards" id="cards"></div></section><section><h2>Relationships</h2><div id="relationships"></div></section></main>
<script>const payload = __PAYLOAD__;
const svgNS = 'http://www.w3.org/2000/svg', width = 1200, height = 660, maxGraphNodes = 180, maxCards = 300;
const levelTypes = {context:new Set(['person','software_system','external_system']),container:new Set(['container','datastore']),component:new Set(['component']),code:new Set(['code'])};
const byId = new Map(payload.elements.map(x => [x.id,x]));
const level = document.querySelector('#level'), focus = document.querySelector('#focus'), cards = document.querySelector('#cards'), summary = document.querySelector('#summary'), relationshipBox = document.querySelector('#relationships'), graph = document.querySelector('#architecture-graph');
let viewport = {x:0,y:0,scale:1}, drag = null;
function esc(value) { return String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])); }
function desc(id, ancestor) { let current=id, seen=new Set; while(current && !seen.has(current)) { if(current===ancestor) return true; seen.add(current); current=(byId.get(current)||{}).parent; } return false; }
function ancestor(id, types) { let current=id, seen=new Set; while(current && !seen.has(current)) { seen.add(current); const item=byId.get(current); if(!item) return null; if(types.has(item.c4_type)) return current; current=item.parent; } return null; }
function nextLevel(type) { return ({software_system:'container',external_system:'container',container:'component',component:'code',datastore:'component'})[type] || null; }
function visible() { const wanted=levelTypes[level.value], selected=focus.value; return payload.elements.filter(x => wanted.has(x.c4_type) && (!selected || desc(x.id,selected))); }
function rolledRelations(selected) { const ids=new Set(selected.map(x=>x.id)), types=levelTypes[level.value], all=[], observed=level.value==='code' ? payload.observed_code_relations : payload.observed_relations; for(const r of observed) all.push({...r, origin:'observed', evidence_count:r.evidence.length}); for(const r of payload.declared_relations) all.push({...r, origin:'declared', evidence_count:0}); const merged=new Map; for(const r of all) { const s=ancestor(r.source,types), t=ancestor(r.target,types); if(!s||!t||s===t||!ids.has(s)||!ids.has(t)) continue; const key=[s,t,r.kind,r.origin].join('|'); const prior=merged.get(key)||{source:s,target:t,kind:r.kind,origin:r.origin,evidence_count:0}; prior.evidence_count+=r.evidence_count; merged.set(key,prior); } return [...merged.values()].sort((a,b)=>a.source.localeCompare(b.source)||a.target.localeCompare(b.target)||a.kind.localeCompare(b.kind)); }
function svgNode(name, attrs={}) { const n=document.createElementNS(svgNS,name); for(const [key,value] of Object.entries(attrs)) n.setAttribute(key,String(value)); return n; }
function nodeColor(type) { return ({software_system:'#3867d6',external_system:'#7c3aed',container:'#0284c7',datastore:'#0f766e',component:'#2563eb',code:'#64748b',person:'#be123c'})[type] || '#3867d6'; }
function layout(items, rels) { const nodes=items.map((item,index)=>({id:item.id,item,x:width/2+260*Math.cos((Math.PI*2*index)/Math.max(items.length,1)),y:height/2+210*Math.sin((Math.PI*2*index)/Math.max(items.length,1)),vx:0,vy:0})); if(nodes.length===1) { nodes[0].x=width/2; nodes[0].y=height/2; return nodes; } const byNode=new Map(nodes.map(n=>[n.id,n])); for(let step=0; step<180; step++) { for(let i=0;i<nodes.length;i++) for(let j=i+1;j<nodes.length;j++) { const a=nodes[i],b=nodes[j],dx=b.x-a.x||.1,dy=b.y-a.y||.1,d2=dx*dx+dy*dy,force=9000/Math.max(d2,400); a.vx-=dx*force/Math.sqrt(d2); a.vy-=dy*force/Math.sqrt(d2); b.vx+=dx*force/Math.sqrt(d2); b.vy+=dy*force/Math.sqrt(d2); } for(const rel of rels) { const a=byNode.get(rel.source),b=byNode.get(rel.target); if(!a||!b) continue; const dx=b.x-a.x,dy=b.y-a.y,dist=Math.hypot(dx,dy)||1,force=(dist-250)*.012; a.vx+=dx/dist*force; a.vy+=dy/dist*force; b.vx-=dx/dist*force; b.vy-=dy/dist*force; } for(const n of nodes) { n.x=Math.max(105,Math.min(width-105,n.x+n.vx)); n.y=Math.max(55,Math.min(height-55,n.y+n.vy)); n.vx*=.72; n.vy*=.72; } } return nodes; }
function resetViewport() { viewport={x:0,y:0,scale:1}; const group=graph.querySelector('.viewport'); if(group) group.setAttribute('transform','translate(0 0) scale(1)'); }
function applyViewport() { const group=graph.querySelector('.viewport'); if(group) group.setAttribute('transform',`translate(${viewport.x} ${viewport.y}) scale(${viewport.scale})`); }
function renderGraph(items, rels) { graph.replaceChildren(); if(!items.length) return; if(items.length>maxGraphNodes) { const message=svgNode('text',{x:width/2,y:height/2,'text-anchor':'middle',fill:'#526174','font-size':18}); message.textContent=`${items.length} elements are too many for one graph. Focus a component to continue.`; graph.append(message); return; } const defs=svgNode('defs'), marker=svgNode('marker',{id:'arrow',viewBox:'0 -5 10 10',refX:9,refY:0,markerWidth:7,markerHeight:7,orient:'auto'}); marker.append(svgNode('path',{d:'M0,-5L10,0L0,5',fill:'#526174'})); defs.append(marker); graph.append(defs); const group=svgNode('g',{class:'viewport'}); graph.append(group); const nodes=layout(items,rels), byNode=new Map(nodes.map(n=>[n.id,n])); const parallel=new Map(); for(const rel of rels) { const key=[rel.source,rel.target].join('|'); parallel.set(key,(parallel.get(key)||0)+1); } const seen=new Map(); for(const rel of rels) { const a=byNode.get(rel.source),b=byNode.get(rel.target); if(!a||!b) continue; const key=[rel.source,rel.target].join('|'), ordinal=seen.get(key)||0; seen.set(key,ordinal+1); const dx=b.x-a.x,dy=b.y-a.y,dist=Math.hypot(dx,dy)||1,nx=-dy/dist,ny=dx/dist,bend=(ordinal-(parallel.get(key)-1)/2)*26; const startX=a.x+dx/dist*76,startY=a.y+dy/dist*30,endX=b.x-dx/dist*76,endY=b.y-dy/dist*30,midX=(startX+endX)/2+nx*bend,midY=(startY+endY)/2+ny*bend; const edge=svgNode('path',{class:`edge ${rel.origin}`,d:`M ${startX} ${startY} Q ${midX} ${midY} ${endX} ${endY}`,'marker-end':'url(#arrow)'}); edge.append(svgNode('title')); edge.lastChild.textContent=`${rel.source} ${rel.kind} ${rel.target}${rel.evidence_count ? ` (${rel.evidence_count} evidence)` : ''}`; group.append(edge); } for(const node of nodes) { const item=node.item, card=svgNode('g',{class:'node',transform:`translate(${node.x-76} ${node.y-30})`,role:'button',tabindex:0}); card.append(svgNode('rect',{width:152,height:60,stroke:nodeColor(item.c4_type)})); const type=svgNode('text',{class:'type',x:11,y:19}); type.textContent=item.c4_type.replace('_',' '); const name=svgNode('text',{class:'name',x:11,y:43}); name.textContent=item.name.length>19 ? `${item.name.slice(0,18)}…` : item.name; card.append(type,name); const drill=()=>{const next=nextLevel(item.c4_type);if(!next)return;focus.value=item.id;level.value=next;render();}; card.onclick=event=>{event.stopPropagation();drill();}; card.onkeydown=event=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();drill();}}; const tip=svgNode('title'); tip.textContent=`${item.name} — ${item.id}`; card.append(tip); group.append(card); } resetViewport(); }
function renderFocus() { const before=focus.value; focus.innerHTML='<option value="">Entire system</option>'+payload.elements.filter(x=>x.c4_type!=='code').map(x=>`<option value="${esc(x.id)}">${esc(x.name)} — ${esc(x.id)}</option>`).join(''); focus.value=byId.has(before)?before:''; }
function drill(id) { const item=byId.get(id), next=item && nextLevel(item.c4_type); if(!next) return; focus.value=item.id; level.value=next; render(); }
function codeSubgraph(selected, rels) { if(level.value!=='code' || selected.length<=maxGraphNodes || !focus.value) return {elements:selected,relations:rels}; const score=new Map(selected.map(x=>[x.id,0])); for(const rel of rels) { score.set(rel.source,(score.get(rel.source)||0)+rel.evidence_count); score.set(rel.target,(score.get(rel.target)||0)+rel.evidence_count); } const ids=new Set([...selected].sort((a,b)=>(score.get(b.id)-score.get(a.id))||a.id.localeCompare(b.id)).slice(0,maxGraphNodes).map(x=>x.id)); return {elements:selected.filter(x=>ids.has(x.id)),relations:rels.filter(r=>ids.has(r.source)&&ids.has(r.target))}; }
function render() { const selected=visible(), rels=rolledRelations(selected), subgraph=codeSubgraph(selected,rels), isLargeCode=level.value==='code'&&selected.length>maxGraphNodes; summary.textContent=`${selected.length} ${level.value} element(s), ${rels.length} visible relationship(s). ${isLargeCode&&focus.value?`Showing the ${subgraph.elements.length} most connected nodes. `:''}Click a node or card to drill down.`; renderGraph(subgraph.elements,subgraph.relations); const cardElements=isLargeCode&&focus.value?subgraph.elements:selected; cards.innerHTML=!selected.length?'<div class="empty">No elements at this level and focus.</div>':selected.length>maxCards&&!focus.value?`<div class="empty">${selected.length} elements are too many for a card list. Focus a component to continue.</div>`:cardElements.map(x=>`<button class="card" data-id="${esc(x.id)}"><div class="type">${esc(x.c4_type)}</div><div class="name">${esc(x.name)}</div><div class="id">${esc(x.id)}</div></button>`).join(''); for(const card of cards.querySelectorAll('[data-id]')) card.onclick=()=>drill(card.dataset.id); relationshipBox.innerHTML=rels.length?`<table><thead><tr><th>Source</th><th>Relationship</th><th>Target</th><th>Evidence</th></tr></thead><tbody>${(isLargeCode&&focus.value?subgraph.relations:rels).map(r=>`<tr><td>${esc(r.source)}</td><td class="${esc(r.origin)}">${esc(r.kind)} (${esc(r.origin)})</td><td>${esc(r.target)}</td><td>${r.evidence_count||'—'}</td></tr>`).join('')}</tbody></table>`:'<div class="empty">No relationships at this zoom level.</div>'; }
graph.onwheel=event=>{event.preventDefault(); const factor=event.deltaY<0?1.12:.89; viewport.scale=Math.max(.35,Math.min(3,viewport.scale*factor)); applyViewport();}; graph.onpointerdown=event=>{if(event.target===graph){drag={x:event.clientX,y:event.clientY,baseX:viewport.x,baseY:viewport.y};graph.classList.add('dragging');graph.setPointerCapture(event.pointerId);}}; graph.onpointermove=event=>{if(!drag)return; const rect=graph.getBoundingClientRect(); viewport.x=drag.baseX+(event.clientX-drag.x)*width/rect.width;viewport.y=drag.baseY+(event.clientY-drag.y)*height/rect.height;applyViewport();}; graph.onpointerup=event=>{drag=null;graph.classList.remove('dragging');if(graph.hasPointerCapture(event.pointerId))graph.releasePointerCapture(event.pointerId);}; graph.ondblclick=event=>{if(event.target===graph)resetViewport();};
renderFocus(); level.onchange=render; focus.onchange=render; document.querySelector('#reset').onclick=()=>{focus.value='';render()}; render();
</script></body></html>"""


def write_architecture_html(projection: dict[str, Any], output_path: Path) -> None:
    """Write an offline, browser-ready C4 graph explorer without external assets."""
    payload = {
        "elements": projection.get("elements", []),
        "observed_relations": projection.get("observed_relations", []),
        "observed_code_relations": projection.get("observed_code_relations", []),
        "declared_relations": projection.get("declared_relations", []),
    }
    encoded = json.dumps(payload, ensure_ascii=False).replace("<", "\\u003c")
    write_text_atomic(output_path, _TEMPLATE.replace("__PAYLOAD__", encoded))
