"""Interactive multi-level C4 architecture diff renderer."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from graphify.paths import write_text_atomic


_TEMPLATE = """<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Graphify C4 Architecture Diff</title><script src="https://unpkg.com/vis-network@9.1.6/standalone/umd/vis-network.min.js"></script>
<style>body{margin:0;background:#0b1020;color:#e5e7eb;font:13px system-ui,sans-serif}#graph{position:fixed;inset:0 355px 0 0}#side{position:fixed;right:0;top:0;bottom:0;width:320px;padding:17px;background:#11182b;border-left:1px solid #29334b;overflow:auto}h1{font-size:18px;margin:0 0 8px}h2{font-size:13px;margin:20px 0 8px;color:#d1d5db}.muted{color:#9ca3af;line-height:1.45}.field{margin:7px 0;line-height:1.4}select,input{background:#0b1020;border:1px solid #34415e;color:#e5e7eb;border-radius:5px;padding:7px;width:100%}label{display:block;margin:12px 0 6px;color:#cbd5e1}.check{display:flex;align-items:center;gap:8px;margin-top:12px}.check input{width:auto}.key{display:flex;gap:8px;align-items:center;margin:6px 0}.dot{width:10px;height:10px;border-radius:50%}.edge{width:25px;border-top:2px solid}code{font-size:11px;color:#cbd5e1;word-break:break-word}</style></head><body><div id="graph"></div><aside id="side"><h1>C4 Architecture Diff</h1><div class="muted">Select a level or double-click a node to drill down. The graph shows changes by default; enable unchanged facts for context.</div><label>Level<select id="level"><option value="context">Context</option><option value="container">Container</option><option value="component" selected>Component</option><option value="code">Code</option></select></label><label class="check"><input id="unchanged" type="checkbox"> Show unchanged facts</label><div id="stats" class="muted"></div><h2>Legend</h2><div class="key"><i class="dot" style="background:#22c55e"></i>Added</div><div class="key"><i class="dot" style="background:#ef4444"></i>Removed</div><div class="key"><i class="dot" style="background:#f59e0b"></i>Modified / descendants changed</div><div class="key"><i class="edge" style="border-color:#22c55e"></i>Added relation</div><div class="key"><i class="edge" style="border-color:#ef4444;border-top-style:dashed"></i>Removed relation</div><h2>Node</h2><div id="info" class="muted">Click a node to inspect its direct and descendant changes.</div></aside><script>
const payload=__PAYLOAD__, order=['context','container','component','code'], color={added:'#22c55e',removed:'#ef4444',modified:'#f59e0b',unchanged:'#4E79A7'};
const level=document.querySelector('#level'), unchanged=document.querySelector('#unchanged'), info=document.querySelector('#info'), stats=document.querySelector('#stats'), nodes=new vis.DataSet(), edges=new vis.DataSet();
const network=new vis.Network(document.querySelector('#graph'),{nodes,edges},{physics:{solver:'forceAtlas2Based',forceAtlas2Based:{gravitationalConstant:-75,springLength:145,springConstant:.075},stabilization:{iterations:220}},interaction:{dragNodes:true,hover:true,hideEdgesOnDrag:true},nodes:{shape:'dot',borderWidth:1.5},edges:{smooth:{type:'continuous'}}});
let current=[], currentRelations=[];
function delta(item){const d=item.descendant_delta||{};return (d.added||0)+(d.removed||0)+(d.modified||0)}
function rankRelation(a,b){const weight=x=>(x.status==='added'||x.status==='removed'?3:x.status==='modified'?2:1);return weight(b)-weight(a)||b.after_evidence_count-a.after_evidence_count||a.source.localeCompare(b.source)}
function choose(elements, relations, limit){if(elements.length<=limit)return elements;const byId=new Map(elements.map(x=>[x.id,x])),adj=new Map(elements.map(x=>[x.id,[]]));for(const r of relations){if(adj.has(r.source))adj.get(r.source).push(r);if(adj.has(r.target))adj.get(r.target).push(r)}const ranked=[...elements].sort((a,b)=>(a.status==='unchanged')-(b.status==='unchanged')||delta(b)-delta(a)||a.id.localeCompare(b.id)),ids=new Set,frontier=new Set,add=id=>{if(ids.size>=limit||ids.has(id)||!byId.has(id))return false;ids.add(id);for(const r of adj.get(id)||[])frontier.add(r);return true},grow=()=>{while(ids.size<limit){let best=null;for(const r of frontier){const a=ids.has(r.source),b=ids.has(r.target);if(a===b)continue;if(!best||rankRelation(r,best)<0)best=r}if(!best)break;add(ids.has(best.source)?best.target:best.source)}};for(const item of ranked){if(ids.size>=limit)break;if(add(item.id))grow()}return elements.filter(item=>ids.has(item.id))}
function render(){const data=payload.levels[level.value], show=unchanged.checked, relations=data.relations.filter(r=>show||r.status!=='unchanged'), candidates=data.elements.filter(item=>show||item.status!=='unchanged'||relations.some(r=>r.source===item.id||r.target===item.id)), limit=level.value==='code'?220:500, selected=choose(candidates,relations,limit), ids=new Set(selected.map(x=>x.id));current=selected;currentRelations=relations.filter(r=>ids.has(r.source)&&ids.has(r.target));nodes.clear();edges.clear();nodes.add(selected.map(item=>({id:item.id,label:item.name,title:`${item.name}\n${item.id}`,size:12+Math.min(28,delta(item)/3),color:{background:color[item.status],border:color[item.status],highlight:{background:'#fff',border:color[item.status]}},font:{color:'#e5e7eb'},_item:item})));edges.add(currentRelations.map((r,index)=>({id:index,from:r.source,to:r.target,arrows:'to',dashes:r.status==='removed',width:r.status==='unchanged'?1:2,color:{color:color[r.status],opacity:r.status==='unchanged'?.28:.9},title:`${r.kind} (${r.status}) — ${r.before_evidence_count} → ${r.after_evidence_count}`})));const changedNodes=data.elements.filter(x=>x.status!=='unchanged').length,changedRelations=data.relations.filter(x=>x.status!=='unchanged').length;stats.textContent=`${data.elements.length} ${level.value} nodes · ${changedNodes} changed · ${changedRelations} changed relations${selected.length<data.elements.length?` · showing ${selected.length}`:''}`;info.textContent='Click a node to inspect its direct and descendant changes.';network.setOptions({physics:{enabled:true}});network.stabilize(180);network.once('stabilizationIterationsDone',()=>network.setOptions({physics:{enabled:false}}));}
network.on('click',params=>{if(!params.nodes.length)return;const item=(nodes.get(params.nodes[0])||{})._item;if(!item)return;const d=item.descendant_delta||{};info.innerHTML=`<div class="field"><b>${item.name}</b></div><div class="field"><code>${item.id}</code></div><div class="field">Direct status: ${item.direct_status}</div><div class="field">Descendants: +${d.added||0} / −${d.removed||0} / ~${d.modified||0}</div>${item.source_file?`<div class="field">${item.source_file}</div>`:''}`});
network.on('doubleClick',params=>{if(!params.nodes.length)return;const index=order.indexOf(level.value);if(index>=0&&index<order.length-1){level.value=order[index+1];render()}});level.onchange=render;unchanged.onchange=render;render();
</script></body></html>"""


def write_architecture_diff_html(diff: dict[str, Any], output_path: Path) -> None:
    """Write an interactive renderer covering every C4 level in a diff payload."""
    encoded = json.dumps(diff, ensure_ascii=False).replace("<", "\\u003c")
    write_text_atomic(output_path, _TEMPLATE.replace("__PAYLOAD__", encoded))
